name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install example dependencies
      run: npm run install-example-dependencies
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Lint
      run: npm run lint
    - name: Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '12.x'
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}